"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/client";
import { defaults, loadSetup, saveSetup, type Confidence, type Setup as StudySetup } from "@/lib/onboarding";
import styles from "./setup.module.css";

const dayLabels=["S","M","T","W","T","F","S"];
const dayNames=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const TOTAL_STEPS=6;

type CloudSettings={
 target_exam_period?:string|null;target_exam_date:string|null;daily_target_minutes:number|null;study_days:number[]|null;rest_days:number[]|null;confidence:Partial<StudySetup["confidence"]>|null;reminder_enabled:boolean|null;reminder_time:string|null;first_message_seen?:boolean|null;onboarding_completed:boolean|null;
};

function mergeCloud(local:StudySetup,cloud:CloudSettings):StudySetup{return{...local,targetExamPeriod:cloud.target_exam_period||local.targetExamPeriod,targetExamDate:cloud.target_exam_date||local.targetExamDate,dailyTargetMinutes:cloud.daily_target_minutes??local.dailyTargetMinutes,studyDays:cloud.study_days??local.studyDays,restDays:cloud.rest_days??local.restDays,confidence:{...local.confidence,...(cloud.confidence||{})},reminderEnabled:cloud.reminder_enabled??local.reminderEnabled,reminderTime:cloud.reminder_time?String(cloud.reminder_time).slice(0,5):local.reminderTime,firstMessageSeen:cloud.first_message_seen??local.firstMessageSeen,completed:cloud.onboarding_completed??local.completed}}

export function Setup(){
 const router=useRouter();
 const[step,setStep]=useState(0);const[study,setStudy]=useState<StudySetup>(defaults);const[email,setEmail]=useState("");const[busy,setBusy]=useState(false);const[status,setStatus]=useState("");
 useEffect(()=>{setStudy(loadSetup());if(!isSupabaseConfigured())return;let cancelled=false;(async()=>{try{const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user||cancelled){router.replace("/sign-in");return}setEmail(user.email||"");const{data}=await supabase.from("cele_settings").select("target_exam_period,target_exam_date,daily_target_minutes,study_days,rest_days,confidence,reminder_enabled,reminder_time,first_message_seen,onboarding_completed").eq("user_id",user.id).maybeSingle();if(data&&!cancelled){const merged=mergeCloud(loadSetup(),data as CloudSettings);setStudy(merged);saveSetup(merged);if(merged.completed)router.replace("/")}}catch{}})();return()=>{cancelled=true}},[router]);
 function patch(values:Partial<StudySetup>){const next={...study,...values};setStudy(next);saveSetup(next)}
 function toggleDay(day:number){const active=study.studyDays.includes(day);const studyDays=active?study.studyDays.filter(d=>d!==day):[...study.studyDays,day].sort();const restDays=[0,1,2,3,4,5,6].filter(d=>!studyDays.includes(d));patch({studyDays,restDays})}
 function setConfidence(key:keyof StudySetup["confidence"],value:Confidence){patch({confidence:{...study.confidence,[key]:value}})}
 const restLabel=useMemo(()=>study.restDays.length?study.restDays.map(d=>dayNames[d]).join(", "):"No planned rest day",[study.restDays]);
 function next(){setStatus("");setStep(s=>Math.min(TOTAL_STEPS-1,s+1));window.scrollTo({top:0,behavior:"smooth"})}
 function back(){setStatus("");setStep(s=>Math.max(0,s-1));window.scrollTo({top:0,behavior:"smooth"})}
 async function finish(){setBusy(true);setStatus("");try{if(!isSupabaseConfigured())throw new Error("Supabase is not configured on this device.");const supabase=createClient();const{data:{user},error:userError}=await supabase.auth.getUser();if(userError||!user)throw userError||new Error("Your session expired. Sign in again.");const completed:StudySetup={...study,firstMessageSeen:true,completed:true};const profile=await supabase.from("profiles").upsert({id:user.id,display_name:"Kean"});if(profile.error)throw profile.error;let settings=await supabase.from("cele_settings").upsert({user_id:user.id,target_exam_period:completed.targetExamPeriod,target_exam_date:completed.targetExamDate||null,daily_target_minutes:completed.dailyTargetMinutes,study_days:completed.studyDays,rest_days:completed.restDays,confidence:completed.confidence,reminder_enabled:completed.reminderEnabled,reminder_time:completed.reminderTime,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,first_message_seen:true,onboarding_completed:true,onboarding_version:2});if(settings.error&&/column|schema cache/i.test(settings.error.message)){settings=await supabase.from("cele_settings").upsert({user_id:user.id,target_exam_date:completed.targetExamDate||null,daily_target_minutes:completed.dailyTargetMinutes,study_days:completed.studyDays,rest_days:completed.restDays,confidence:completed.confidence,reminder_enabled:completed.reminderEnabled,reminder_time:completed.reminderTime,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,onboarding_completed:true})}if(settings.error)throw settings.error;saveSetup(completed);router.replace("/");router.refresh()}catch(e){setStatus(e instanceof Error?e.message:"Could not finish setup.")}finally{setBusy(false)}}
 const canNext=step===1?Boolean(study.targetExamPeriod.trim()):step===2?study.studyDays.length>0:true;
 return <div className={styles.stage}><div className={styles.shell}>
   <header className={styles.top}><div className={styles.brand}><img src="/assets/brand/logo-mark.png" alt=""/><span>Kean I Help?</span></div><span className={styles.step}>{step+1} / {TOTAL_STEPS}</span></header>
   <div className={styles.progress}><span style={{width:`${((step+1)/TOTAL_STEPS)*100}%`}}/></div>
   <main className={styles.content}>
    {step===0&&<section className={styles.intro}><img className={styles.jace} src="/assets/jace/stickers/default.png" alt="Jace sticker"/><small>YOUR REVIEWER</small><h1>Hey, Kean.</h1><p>I made this so you don’t have to figure everything out at once. We’ll set up the reviewer first, then you can just focus on the next thing.</p><div className={styles.note}>Signed in as <b>{email||"Kean’s private account"}</b></div></section>}
    {step===1&&<section><small>YOUR TARGET</small><h1>When are you taking CELE?</h1><p className={styles.lead}>We’ll use this for pacing and the countdown. The exact date can stay blank until PRC publishes it.</p><label className={styles.field}>Target exam period<input value={study.targetExamPeriod} onChange={e=>patch({targetExamPeriod:e.target.value})} placeholder="April 2027"/></label><label className={styles.field}>Exact exam date <span>optional</span><input type="date" value={study.targetExamDate} onChange={e=>patch({targetExamDate:e.target.value})}/></label></section>}
    {step===2&&<section><small>YOUR RHYTHM</small><h1>How should studying fit into your week?</h1><p className={styles.lead}>This is a plan, not a streak contract. Change it anytime.</p><div className={styles.block}><b>Study days</b><div className={styles.days}>{dayLabels.map((d,i)=><button key={i} className={study.studyDays.includes(i)?styles.selected:""} onClick={()=>toggleDay(i)}>{d}</button>)}</div><span>Rest: {restLabel}</span></div><div className={styles.block}><b>Daily target</b><div className={styles.segment}>{[30,45,60,90].map(v=><button key={v} className={study.dailyTargetMinutes===v?styles.selected:""} onClick={()=>patch({dailyTargetMinutes:v})}>{v} min</button>)}</div></div></section>}
    {step===3&&<section><small>STARTING POINT</small><h1>How do these feel right now?</h1><p className={styles.lead}>No test yet. This is only your first impression; real practice data will replace it later.</p><div className={styles.confidence}>{([['structural','Structural Analysis & Design'],['mste','Math, Surveying, Transportation & Construction'],['hge','Hydraulics & Geotechnical']] as const).map(([key,label])=><div key={key} className={styles.confidenceRow}><b>{label}</b><div className={styles.segment}>{([['needs-work','Not confident'],['okay','Okay'],['confident','Confident']] as const).map(([value,text])=><button key={value} className={study.confidence[key]===value?styles.selected:""} onClick={()=>setConfidence(key,value)}>{text}</button>)}</div></div>)}</div></section>}
    {step===4&&<section><small>GENTLE REMINDERS</small><h1>Want a study reminder?</h1><p className={styles.lead}>Only on planned study days. Rest days stay protected, and there are no guilt messages.</p><div className={styles.reminderChoice}><button className={study.reminderEnabled?styles.selected:""} onClick={()=>patch({reminderEnabled:true})}>Yes, remind me</button><button className={!study.reminderEnabled?styles.selected:""} onClick={()=>patch({reminderEnabled:false})}>Not now</button></div>{study.reminderEnabled&&<label className={styles.field}>Preferred time<input type="time" value={study.reminderTime} onChange={e=>patch({reminderTime:e.target.value})}/></label>}<div className={styles.note}>We won’t ask for browser notification permission during setup. That happens later, with context.</div></section>}
    {step===5&&<section className={styles.final}><img className={styles.jaceFinal} src="/assets/jace/stickers/gentle.png" alt="Jace gentle sticker"/><small>ONE THING BEFORE YOU START</small><blockquote>You don’t need to know everything today. We’ll build it little by little. I’m here.</blockquote><span>— Jace</span></section>}
   </main>
   {status&&<div className={styles.status} role="status">{status}</div>}
   <footer className={styles.actions}>{step>0?<button className={styles.secondary} onClick={back} disabled={busy}>Back</button>:<span/>}{step<TOTAL_STEPS-1?<button className={styles.primary} onClick={next} disabled={!canNext}>Continue</button>:<button className={styles.primary} onClick={finish} disabled={busy}>{busy?"Saving…":"Start reviewing"}</button>}</footer>
 </div></div>
}
